"""Initial migration

Revision ID: 7234eb73aa3a
Revises: 
Create Date: 2024-12-24 20:29:31.819897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7234eb73aa3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localtime', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('feelslike_c', sa.Float(), nullable=False),
    sa.Column('cloud', sa.Float(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_data1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localtime', sa.String(length=100), nullable=False),
    sa.Column('temp_c', sa.String(length=100), nullable=False),
    sa.Column('wind_kph', sa.String(length=100), nullable=False),
    sa.Column('humidity', sa.String(length=100), nullable=False),
    sa.Column('feelslike_c', sa.String(length=100), nullable=False),
    sa.Column('cloud', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_data_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localtime', sa.String(length=100), nullable=False),
    sa.Column('temp_c', sa.String(length=100), nullable=False),
    sa.Column('wind_kph', sa.String(length=100), nullable=False),
    sa.Column('humidity', sa.String(length=100), nullable=False),
    sa.Column('feelslike_c', sa.String(length=100), nullable=False),
    sa.Column('cloud', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data_1')
    op.drop_table('weather_data1')
    op.drop_table('weather_data')
    # ### end Alembic commands ###
